### ISSUE TITLE
Export ADDM enhancement

### ISSUE THREAD

**Issue by raffaelloferrari** [amreo/ercole-services#64]
**Is your feature request related to a problem? Please describe.**
When we generate XLS of tab ADDM column benefit contain dot instead of comma and it's not ordered by benefit percentage. 

**Describe the solution you'd like**
Fix it

**Comment by amreo** [comment]
Why there should be the comma instead of the dot? The standard symbol used to separe the decimals is the dot.

**Comment by raffaelloferrari** [comment]
Because Excel need comma as decimal separetor

**Comment by amreo** [comment]
I've some tests with libreoffice calc and I discovered that the problem is that the benefit column is written as text instead of a number, so libreoffice doesn't see it as a numeric value and doesn't localize it rightly. The problem is inherithed from the fact that the values is stored as string instead of a float.
